language: elm
elm:
- latest-0.19.1
elm-test: 0.19.1
elm-format: 0.8.2
script:
- npm run build
- npm test
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    branch: main
env:
  global:
    secure: ikV4+X2wu1aZ36lyF7xSyaD6xvz12P/2zeOZf1yUF/xDa7lGFqM0F5ABABODPkSLfgvXA6UY9ozn4EO2fiJqWQi3RuaUC25SgMYFtbfqW8KjOt2hN4enjTm+L7q2aaiLzoT0T+dPhNogaHAkUFciKIp7fZYU+wbHbi3udwWBKkCOQ7tH7XIa234EDfgXjnGldGJ+1jxMmSn9SO4PhNakEAbMf3odDRpna5vCnrbW1eKtPt/qNDuSMoLgHQzOtr8xa2jR4CmbZWwcbHDHYL/jFqo2IQCDan/2LFC1HL58eWENANaw9Ax3Pgxm6jUcm/XIvH+YrcgcTIKUruRL44ZZDSpiEIchIzyiRbU+83hz8vt3v7Pn5ZsU3kfA7umMaG/34bYj9K6C7UDEuPuh6vYNPMcPuBDztXIXbIdZ6vcTZ/+RAlz46E82OEI7M1gvcMBLRIFmCLoY3R9yqKcGZ1gA6/1grD3IFZIS23Ve+MdhxRa2Z2u98Ci/L87pWZF+2PPa0YWKVuC+GIv5kbORya+SnHJLb0rf0GCrDwYfN1R46NbZLVpfBcxnyO44d1R+nTNelTJWQbZgmpfoBkqf7CvmAqBdtR/dmo1WVKYLOpEaoQBIrD73iuH0geOt2V12MamVYvmFFiuWjlOtGys7UvXuWPjLDoOSLjzqt1pq2crDrY4=
