[build]
  publish = "dist/"
  command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm install --no-optional && npm run build"

[dev]
  command = "yarn start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
